title: Daniel Opitz - Blog
description: Developer, Trainer, Open Source Contributor
url: https://odan.github.io

github:
  is_project_page: false

x:
  username: dopitz

comments: true

image:
  path: https://odan.github.io/assets/images/post_default.png
